# ZAXSITZ Dark Theme
background=#0a0a0a
foreground=#aaaaaa
cursor=#aaaaaa
color0=#0a0a0a
color1=#cc0000
color2=#00cc00
color3=#cccc00
color4=#0000cc
color5=#cc00cc
color6=#00cccc
color7=#cccccc
color8=#444444
color9=#ff4444
color10=#44ff44
color11=#ffff44
color12=#4444ff
color13=#ff44ff
color14=#44ffff
color15=#ffffff
